const pokemonSeedData = [
    {
        name: 'Bulbasaur',
        type: 'Grass',
        description: 'Bulbasaur can be seen napping in bright sunlight. There is a seed on its back. By soaking up the suns rays, the seed grows progressively larger.',
        image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/1.png',
        region: 'Kanto',
    },
    {
        name: 'Ivysaur',
        type: 'Grass',
        description: 'There is a bud on this Pokemons back. To support its weight, Ivysaurs legs and trunk grow thick and strong. If it starts spending more time lying in the sunlight, its a sign that the bud will bloom into a large flower soon.',
        image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/2.png',
        region: 'Kanto',
    },
    {
        name: 'Venusaur',
        type: 'Grass',
        description: 'There is a large flower on Venusaur s back. The flower is said to take on vivid colors if it gets plenty of nutrition and sunlight. The flower s aroma soothes the emotions of people.',
        image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/3.png',
        region: 'Kanto',
    },
    {
        name: 'Charmander',
        type: 'Fire',
        description: 'The flame that burns at the tip of its tail is an indication of its emotions. The flame wavers when Charmander is enjoying itself. If the Pokemon becomes enraged, the flame burns fiercely.',
        image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/4.png',
        region: 'Kanto',
    },
    {
        name: 'Charmeleon',
        type: 'Fire',
        description: 'Charmeleon mercilessly destroys its foes using its sharp claws. If it encounters a strong foe, it turns aggressive. In this excited state, the flame at the tip of its tail flares with a bluish white color.',
        image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/5.png',
        region: 'Kanto',
    },
    {
        name: 'Charizard',
        type: 'Fire',
        description: 'Charizard flies around the sky in search of powerful opponents. It breathes fire of such great heat that it melts anything. However, it never turns its fiery breath on any opponent weaker than itself.',
        image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/6.png',
        region: 'Kanto',
    },
    {
        name: 'Squirtle',
        type: 'Water',
        description: 'Squirtle s shell is not merely used for protection. The shells rounded shape and the grooves on its surface help minimize resistance in water, enabling this Pokemon to swim at high speeds.',
        image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/7.png',
        region: 'Kanto',
    },
    {
        name: 'Wartortle',
        type: 'Water',
        description: 'Its tail is large and covered with a rich, thick fur. The tail becomes increasingly deeper in color as Wartortle ages. The scratches on its shell are evidence of this Pokemons toughness as a battler.',
        image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/8.png',
        region: 'Kanto',
    },
    {
        name: 'Blastoise',
        type: 'Water',
        description: 'Blastoise has water spouts that protrude from its shell. The water spouts are very accurate. They can shoot bullets of water with enough accuracy to strike empty cans from a distance of over 160 feet.',
        image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/9.png',
        region: 'Kanto',
    },
    {
        name: 'Caterpie',
        type: 'Bug',
        description: 'Caterpie has a voracious appetite. It can devour leaves bigger than its body right before your eyes. From its antenna, this Pokemon releases a terrifically strong odor.',
        image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/10.png',
        region: 'Kanto',
    },
    {
        name: 'Metapod',
        type: 'Bug',
        description: 'The shell covering this Pokemons body is as hard as an iron slab. Metapod does not move very much. It stays still because it is preparing its soft innards for evolution inside the hard shell.',
        image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/11.png',
        region: 'Kanto',
    },
    {
        name: 'Butterfree',
        type: 'Bug',

        description: 'Butterfree has a superior ability to search for delicious honey from flowers. It can even search out, extract, and carry honey from flowers that are blooming over six miles from its nest.',

        image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/12.png',
        region: 'Kanto',
    },
    {
        name: 'Weedle',
        type: 'Bug',
        description: 'Weedle has an extremely acute sense of smell. It is capable of distinguishing its favorite kinds of leaves from those it dislikes just by sniffing with its big red proboscis (nose).',
        image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/13.png',
        region: 'Kanto',
    },
    {
        name: 'Kakuna',
        type: 'Bug',
        description: 'Kakuna remains virtually immobile as it clings to a tree. However, on the inside, it is extremely busy as it prepares for its coming evolution. This is evident from how hot the shell becomes to the touch.',
        image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/14.png',
        region: 'Kanto',
    },
    {
        name: 'Beedrill',
        type: 'Bug',
        description: 'Beedrill is extremely territorial. No one should ever approach its nest this Pokemons sharp stinger is capable of jabbing its enemy repeatedly in just a few seconds.',
        image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/15.png',
        region: 'Kanto',
    },
    {
        name: 'Pidgey',
        type: 'Flying',
        description: 'Pidgey has an extremely sharp sense of direction. It is capable of unerringly returning home to its nest, however far it may be removed from its familiar surroundings.',
        image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/16.png',
        region: 'Kanto',
    },
    {
        name: 'Pidgeotto',
        type: 'Flying',
        description: 'Pidgeotto claims a large area as its own territory. This Pokemon flies around, patrolling its living space. If its living space is violated, it shows no mercy in thoroughly punishing the foe with its sharp claws.',
        image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/17.png',
        region: 'Kanto',
    },
    {
        name: 'Pidgeot',
        type: 'Flying',
        description: 'This Pokemon flies at Mach 2 speed, seeking prey. Its large talons are feared as wicked weapons. Pidgeot has an extremely sharp sense of direction.',
        image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/18.png',
        region: 'Kanto',
    },
    {
        name: 'Rattata',
        type: 'Normal',
        description: 'Rattata is cautious in the extreme. Even while it is asleep, it constantly listens by moving its ears around. It is not picky about where it lives - it will make its nest anywhere.',
        image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/19.png',
        region: 'Kanto',
    },
    {
        name: 'Raticate',
        type: 'Normal',
        description: 'Raticate is cautious in the extreme. Even while it is asleep, it constantly listens by moving its ears around. It is not picky about where it lives - it will make its nest anywhere.',
        image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/20.png',
        region: 'Kanto',
    },
    {
        name: 'Spearow',
        type: 'Flying',
        description: 'Spearow has a very loud cry that can be heard over half a mile away. It uses its large beak to peck at its foe. It flaps its short wings busily to stay airborne.',
        image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/21.png',
        region: 'Kanto',
    },
    {
        name: 'Fearow',
        type: 'Flying',
        description: 'Fearow has a terrifically loud cry. It can communicate over distances of many miles. If its high and keening cry is heard echoing all around, it is a sign that they are warning each other of danger.',
        image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/22.png',
        region: 'Kanto',
    },


];

module.exports = pokemonSeedData;